-- MySQL Script generated by MySQL Workbench
-- Sat Nov 12 23:04:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ejer3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ejer3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS ejer3 DEFAULT CHARACTER SET utf8 ;
USE ejer3 ;

-- -----------------------------------------------------
-- Table `ejer3`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ejer3.cliente (
  id_cliente INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(45) NOT NULL,
  dni INT NOT NULL,
  direccion VARCHAR(255) NOT NULL,
  telefono INT NOT NULL,
  PRIMARY KEY (id_cliente))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejer3`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ejer3.reserva (
  id_reserva INT NOT NULL AUTO_INCREMENT,
  fecha_inicio DATE NOT NULL,
  fecha_final DATE NOT NULL,
  precio_total FLOAT NOT NULL,
  cliente_id_cliente INT NOT NULL,
  PRIMARY KEY (id_reserva, cliente_id_cliente),
  INDEX fk_reserva_cliente_idx (cliente_id_cliente ASC) VISIBLE,
  CONSTRAINT fk_reserva_cliente
    FOREIGN KEY (cliente_id_cliente)
    REFERENCES ejer3.cliente (id_cliente)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejer3`.`coche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ejer3.coche (
  id_coche INT NOT NULL AUTO_INCREMENT,
  matricula VARCHAR(45) NOT NULL,
  modelo INT NOT NULL,
  color VARCHAR(45) NOT NULL,
  marca VARCHAR(45) NOT NULL,
  precio FLOAT NOT NULL,
  gasolina FLOAT NOT NULL,
  reserva_id_reserva INT NOT NULL,
  reserva_cliente_id_cliente INT NOT NULL,
  PRIMARY KEY (id_coche, reserva_id_reserva, reserva_cliente_id_cliente),
  INDEX fk_coche_reserva1_idx (reserva_id_reserva ASC, reserva_cliente_id_cliente ASC) VISIBLE,
  CONSTRAINT fk_coche_reserva1
    FOREIGN KEY (reserva_id_reserva , reserva_cliente_id_cliente)
    REFERENCES ejer3.reserva (id_reserva , cliente_id_cliente)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
