-- MySQL Script generated by MySQL Workbench
-- Sat Nov 12 23:09:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ejer2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ejer2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS ejer2 DEFAULT CHARACTER SET utf8 ;
USE ejer2 ;

-- -----------------------------------------------------
-- Table `ejer2`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ejer2.pais (
  id_pais INT NOT NULL AUTO_INCREMENT,
  nombre_pais VARCHAR(45) NOT NULL,
  PRIMARY KEY (id_pais))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejer2`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ejer2.provincia (
  id_provincia INT NOT NULL AUTO_INCREMENT,
  nombre_provincia VARCHAR(45) NOT NULL,
  pais_id_pais INT NOT NULL,
  PRIMARY KEY (id_provincia, pais_id_pais),
  INDEX fk_provincia_pais1_idx (pais_id_pais ASC) VISIBLE,
  CONSTRAINT fk_provincia_pais1
    FOREIGN KEY (pais_id_pais)
    REFERENCES ejer2.pais (id_pais)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejer2`.`localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ejer2.localidad (
  id_localidad INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(45) NOT NULL,
  codigo_postal INT NOT NULL,
  provincia_id_provincia INT NOT NULL,
  PRIMARY KEY (id_localidad, provincia_id_provincia),
  INDEX fk_localidad_provincia1_idx (provincia_id_provincia ASC) VISIBLE,
  CONSTRAINT fk_localidad_provincia1
    FOREIGN KEY (provincia_id_provincia)
    REFERENCES ejer2.provincia (id_provincia)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejer2`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ejer2.empleado (
  id_empleado INT NOT NULL AUTO_INCREMENT,
  nombre_empleado VARCHAR(45) NOT NULL,
  dni INT NOT NULL,
  telefono INT NOT NULL,
  email VARCHAR(45) NOT NULL,
  fecha_alta DATE NOT NULL,
  localidad_id_localidad INT NOT NULL,
  PRIMARY KEY (id_empleado, localidad_id_localidad),
  INDEX fk_empleado_localidad_idx (localidad_id_localidad ASC) VISIBLE,
  CONSTRAINT fk_empleado_localidad
    FOREIGN KEY (localidad_id_localidad)
    REFERENCES ejer2.localidad (id_localidad)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
