-- MySQL Script generated by MySQL Workbench
-- Sat Nov 12 22:31:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ejer1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ejer1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS ejer1 DEFAULT CHARACTER SET utf8 ;
USE ejer1 ;

-- -----------------------------------------------------
-- Table `ejer1`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ejer1.alumno (
  cod_matricula INT NOT NULL,
  nombre VARCHAR(45) NOT NULL,
  dni INT NOT NULL,
  fecha_nacimiento DATE NOT NULL,
  email VARCHAR(45) NOT NULL,
  PRIMARY KEY (cod_matricula))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejer1`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ejer1.profesor(
  idprofesor INT NOT NULL,
  nombre VARCHAR(45) NOT NULL,
  especialidad VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  PRIMARY KEY (idprofesor))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejer1`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ejer1.curso (
  cod_curso INT NOT NULL,
  nombre VARCHAR(45) NOT NULL,
  alumno_cod_matricula INT NOT NULL,
  profesor_idprofesor INT NOT NULL,
  PRIMARY KEY (cod_curso, alumno_cod_matricula, profesor_idprofesor),
  INDEX fk_curso_alumno_idx (alumno_cod_matricula ASC) VISIBLE,
  INDEX fk_curso_profesor1_idx (profesor_idprofesor ASC) VISIBLE,
  CONSTRAINT fk_curso_alumno
    FOREIGN KEY (alumno_cod_matricula)
    REFERENCES ejer1.alumno (cod_matricula)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_curso_profesor1
    FOREIGN KEY (profesor_idprofesor)
    REFERENCES ejer1.profesor (idprofesor)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejer1`.`alumno_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ejer1.alumno_curso (
  alumno_cod_matricula INT NOT NULL,
  curso_cod_curso INT NOT NULL,
  curso_alumno_cod_matricula INT NOT NULL,
  curso_profesor_idprofesor INT NOT NULL,
  PRIMARY KEY (alumno_cod_matricula, curso_cod_curso, curso_alumno_cod_matricula, curso_profesor_idprofesor),
  INDEX fk_alumno_has_curso_curso1_idx (curso_cod_curso ASC, curso_alumno_cod_matricula ASC, curso_profesor_idprofesor ASC) VISIBLE,
  INDEX fk_alumno_has_curso_alumno1_idx (alumno_cod_matricula ASC) VISIBLE,
  CONSTRAINT fk_alumno_has_curso_alumno1
    FOREIGN KEY (alumno_cod_matricula)
    REFERENCES ejer1.alumno (cod_matricula)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_alumno_has_curso_curso1
    FOREIGN KEY (curso_cod_curso , curso_alumno_cod_matricula , curso_profesor_idprofesor)
    REFERENCES ejer1.curso (cod_curso , alumno_cod_matricula , profesor_idprofesor)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

